name: Publish PowerShell Module

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: Install PowerShell
      run: |
        npm install -g pwsh
        pwsh --version

    - name: Install PowerShellGet
      run: |
        pwsh -Command "Install-Module -Name PowerShellGet -Force -SkipPublisherCheck"
        pwsh -Command "Import-Module PowerShellGet"

    - name: Authenticate to PowerShell Gallery
      run: |
        $Password = ConvertTo-SecureString -String ${{ secrets.PSGalleryApiKey }} -AsPlainText -Force
        $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList 'YourGalleryUsername', $Password
        Set-PSRepository -Name 'PSGallery' -Credential $Credential
      shell: pwsh

    - name: Publish Module
      run: |
        Publish-Module -Path . -NuGetApiKey ${{ secrets.PSGalleryApiKey }} -Verbose
      shell: pwsh

    - name: Verify Module
      run: |
        Find-Module -Name SecurePasswordGenerator
      shell: pwsh
