name: Publish PowerShell Module

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PowerShellGet
      run: |
        Install-Module -Name PowerShellGet -Force -SkipPublisherCheck
        Import-Module PowerShellGet
      shell: pwsh

    - name: Authenticate to PowerShell Gallery
      run: |
        $Password = ConvertTo-SecureString -String ${{ secrets.PSGalleryApiKey }} -AsPlainText -Force
        $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList 'siamakhaz', $Password
        Set-PSRepository -Name 'PSGallery' -Credential $Credential
      shell: pwsh

    - name: Publish Module
      run: |
        Publish-Module -Path . -NuGetApiKey ${{ secrets.PSGalleryApiKey }} -Verbose
      shell: pwsh

    - name: Verify Module
      run: |
        Find-Module -Name SecurePasswordGenerator
      shell: pwsh
